services:
  wpilib-base:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wpilib-base
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - JAVA_OPTS=-Xmx2g
    tty: true
    stdin_open: true
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:30003/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
