services:
  eclipse-jdt-ls:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: eclipse-jdt-ls
    ports:
      - "30003:30003"
    volumes:
      - ./workspace:/home/jdtls/workspace
    environment:
      - JAVA_OPTS=-Xmx2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
