# ECS Task Configuration Profiles
# Different resource configurations for different challenge types and environments

profiles:
  # Development/Testing Profile - Minimal resources
  development:
    cpu: "512"
    memory: "1024"
    java_heap_size: "768"
    node_env: "development"
    description: "Minimal resources for development and testing"
    
  # Basic Challenge Profile - Standard FRC challenges
  basic:
    cpu: "1024"
    memory: "2048"
    java_heap_size: "1536"
    node_env: "production"
    description: "Standard resources for basic FRC programming challenges"
    
  # Advanced Challenge Profile - Complex simulations and multiple subsystems
  advanced:
    cpu: "2048"
    memory: "4096"
    java_heap_size: "3072"
    node_env: "production"
    description: "Higher resources for advanced challenges with complex simulations"
    
  # Competition Profile - Full robot simulation with vision processing
  competition:
    cpu: "4096"
    memory: "8192"
    java_heap_size: "6144"
    node_env: "production"
    description: "Maximum resources for competition-level challenges"

# Environment-specific configurations
environments:
  dev:
    execution_role_name: "ecsTaskExecutionRole-dev"
    task_role_name: "ecsTaskRole-dev"
    image_tag: "dev"
    log_retention_days: 7
    
  staging:
    execution_role_name: "ecsTaskExecutionRole-staging"
    task_role_name: "ecsTaskRole-staging"
    image_tag: "staging"
    log_retention_days: 14
    
  production:
    execution_role_name: "ecsTaskExecutionRole-prod"
    task_role_name: "ecsTaskRole-prod"
    image_tag: "latest"
    log_retention_days: 30

# Port configurations
ports:
  editor_api: 30003
  nt3_port: 1735
  nt4_port: 5810
  hal_websocket: 3300
  vnc_port: 5901      # Optional for debugging
  novnc_port: 6901    # Optional for debugging

# Resource limits and constraints
limits:
  max_concurrent_sessions_per_user: 3
  session_timeout_minutes: 120
  idle_timeout_minutes: 30
  max_file_size_mb: 50
  max_workspace_size_mb: 500

# Health check configurations
health_check:
  interval_seconds: 30
  timeout_seconds: 10
  retries: 3
  start_period_seconds: 60
  grace_period_seconds: 30

# Auto-scaling configurations
auto_scaling:
  min_capacity: 0
  max_capacity: 100
  target_cpu_utilization: 70
  target_memory_utilization: 80
  scale_out_cooldown_seconds: 300
  scale_in_cooldown_seconds: 600

# Security configurations
security:
  enable_efs_encryption: true
  enable_logs_encryption: true
  enable_secrets_manager: true
  network_mode: "awsvpc"
  
# Monitoring and alerting
monitoring:
  enable_container_insights: true
  enable_xray_tracing: true
  custom_metrics:
    - session_duration
    - build_success_rate
    - simulation_performance
    - user_activity
