service: frc-challenge-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  
  # Environment variables
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    CHALLENGES_TABLE: ${self:service}-challenges-${self:provider.stage}
    USER_PROGRESS_TABLE: ${self:service}-user-progress-${self:provider.stage}
    CHALLENGE_SESSIONS_TABLE: ${self:service}-challenge-sessions-${self:provider.stage}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    NODE_ENV: ${env:NODE_ENV, 'development'}
    # ECS Configuration
    ECS_CLUSTER_NAME: ${env:ECS_CLUSTER_NAME, 'frc-challenge-cluster'}
    ECS_TASK_DEFINITION: ${env:ECS_TASK_DEFINITION, 'frc-challenge-runtime'}
    PRIVATE_SUBNET_1: ${env:PRIVATE_SUBNET_1}
    PRIVATE_SUBNET_2: ${env:PRIVATE_SUBNET_2}
    CHALLENGE_RUNTIME_SECURITY_GROUP: ${env:CHALLENGE_RUNTIME_SECURITY_GROUP}

    # ALB Configuration
    ALB_LISTENER_ARN: ${env:ALB_LISTENER_ARN}
    ALB_TARGET_GROUP_ARN: ${env:ALB_TARGET_GROUP_ARN}
    ALB_DNS_NAME: ${env:ALB_DNS_NAME}
    VPC_ID: ${env:VPC_ID}

    # CloudFront Configuration
    CLOUDFRONT_DOMAIN_NAME: ${env:CLOUDFRONT_DOMAIN_NAME, ''}
    USE_CLOUDFRONT: ${env:USE_CLOUDFRONT, 'false'}
    
  # IAM permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHALLENGES_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_PROGRESS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHALLENGE_SESSIONS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHALLENGES_TABLE}/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_PROGRESS_TABLE}/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHALLENGE_SESSIONS_TABLE}/index/*"
        - Effect: Allow
          Action:
            - cognito-idp:GetUser
            - cognito-idp:AdminGetUser
          Resource:
            - "arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:provider.environment.COGNITO_USER_POOL_ID}"
        - Effect: Allow
          Action:
            - ecs:RunTask
            - ecs:StopTask
            - ecs:DescribeTasks
            - ecs:ListTasks
            - ecs:TagResource
            - ecs:ExecuteCommand  # For ECS Exec debugging
            - iam:PassRole
          Resource:
            - "arn:aws:ecs:${self:provider.region}:*:cluster/${self:provider.environment.ECS_CLUSTER_NAME}"
            - "arn:aws:ecs:${self:provider.region}:*:task-definition/frc-challenge-runtime:*"
            - "arn:aws:ecs:${self:provider.region}:*:task/*"
            - "arn:aws:iam::*:role/ecsTaskExecutionRole*"
            - "arn:aws:iam::*:role/ecsTaskRole*"
        # ALB permissions for session management
        - Effect: Allow
          Action:
            - elasticloadbalancing:CreateTargetGroup
            - elasticloadbalancing:CreateRule
            - elasticloadbalancing:RegisterTargets
            - elasticloadbalancing:DeregisterTargets
            - elasticloadbalancing:DescribeTargetGroups
            - elasticloadbalancing:DescribeTargetHealth
            - elasticloadbalancing:DescribeRules
            - elasticloadbalancing:DeleteTargetGroup
            - elasticloadbalancing:DeleteRule
            - elasticloadbalancing:AddTags
            - elasticloadbalancing:RemoveTags
            - ec2:DescribeVpcs
            - ec2:DescribeSubnets
            - ec2:DescribeSecurityGroups
          Resource: "*"
        # Lambda invoke permissions for background processes
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage}-containerSetup"

# Lambda functions
functions:
  # Challenge Management
  getChallenges:
    handler: src/handlers/challenges/getChallenges.handler
    events:
      - http:
          path: /challenges
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  getChallengesOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /challenges
          method: options

  getChallenge:
    handler: src/handlers/challenges/getChallenge.handler
    events:
      - http:
          path: /challenges/{id}
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  getChallengeOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /challenges/{id}
          method: options

  # User Progress Management
  getUserProgress:
    handler: src/handlers/progress/getUserProgress.handler
    events:
      - http:
          path: /user/progress
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  getUserProgressOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /user/progress
          method: options

  updateChallengeProgress:
    handler: src/handlers/progress/updateChallengeProgress.handler
    events:
      - http:
          path: /challenges/{id}/progress
          method: put
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  updateChallengeProgressOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /challenges/{id}/progress
          method: options

  # Challenge Sessions
  createChallengeSession:
    handler: src/handlers/sessions/createChallengeSession.handler
    events:
      - http:
          path: /challenges/{id}/sessions
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  createChallengeSessionOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /challenges/{id}/sessions
          method: options

  saveChallengeCode:
    handler: src/handlers/sessions/saveChallengeCode.handler
    events:
      - http:
          path: /sessions/{sessionId}/code
          method: put
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  saveChallengeCodeOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions/{sessionId}/code
          method: options

  # Session Management
  createSession:
    handler: src/handlers/sessions/createSession.handler
    timeout: 30  # API Gateway limit
    events:
      - http:
          path: /sessions
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  containerSetup:
    handler: src/handlers/sessions/containerSetup.handler
    timeout: 900  # 15 minutes for background process
    # No HTTP events - invoked asynchronously

  createSessionOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions
          method: options

  getSession:
    handler: src/handlers/sessions/getSession.handler
    events:
      - http:
          path: /sessions/{sessionId}
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  getSessionOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions/{sessionId}
          method: options

  terminateSession:
    handler: src/handlers/sessions/terminateSession.handler
    events:
      - http:
          path: /sessions/{sessionId}
          method: delete
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  terminateSessionOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions/{sessionId}
          method: options

  listSessions:
    handler: src/handlers/sessions/listSessions.handler
    events:
      - http:
          path: /sessions
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  listSessionsOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions
          method: options

  keepAlive:
    handler: src/handlers/sessions/keepAlive.handler
    events:
      - http:
          path: /sessions/{sessionId}/keepalive
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

  keepAliveOptions:
    handler: src/handlers/cors/options.handler
    events:
      - http:
          path: /sessions/{sessionId}/keepalive
          method: options

  # Scheduled cleanup function (temporarily disabled due to compilation errors)
  # cleanupSessions:
  #   handler: src/handlers/sessions/cleanupSessions.handler
  #   timeout: 300
  #   events:
  #     - schedule: rate(5 minutes)

# CloudFormation resources
resources:
  Resources:
    # API Gateway Authorizer
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoUserPoolAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: !Ref ApiGatewayRestApi
        ProviderARNs:
          - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${self:provider.environment.COGNITO_USER_POOL_ID}"

    # DynamoDB Tables
    ChallengesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CHALLENGES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
          - AttributeName: difficulty
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryIndex
            KeySchema:
              - AttributeName: category
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: DifficultyIndex
            KeySchema:
              - AttributeName: difficulty
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    UserProgressTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_PROGRESS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: challengeId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: challengeId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ChallengeIndex
            KeySchema:
              - AttributeName: challengeId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ChallengeSessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CHALLENGE_SESSIONS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: challengeId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ChallengeIndex
            KeySchema:
              - AttributeName: challengeId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-webpack
  - serverless-offline


custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    packager: npm
